name: certificate_binarizator
description: Creates a binary certificate. Util for representation of certificate as variable list of bytes.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: ">=2.5.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  args: ^1.6.0
  path: ^1.7.0
  shell: ^1.0.1

executables:
  convert_certificate: main